insight/ add project sprint destroy api
BehemothLtd/aio-server pull request #69
Opened 2024-03-15 08:13 UTC by behemoth-phucph

issue: https://github.com/BehemothLtd/aio-server/issues/54

2024-03-18 16:38 UTC, bachdx2812 requested changes
1. trước khi assign vào model thì em dùng hàm `field.IsClean()` để check nếu field ko có lỗi thì mới assign vào. Vdu: 
```
if startDate.IsClean() {
  form.ProjectSprint.StartDate = *startDate.Time()
}
```
2. hình như là validate start date nó ko đơn giản như này đâu nhỉ ?

2024-03-25 16:05 UTC, behemoth-phucph commented on validators/projectSprintCreate.form.go
> +	fmt.Printf("endDate==========================: %v\n", endDate)
đoạn này e đang muốn viết như này 
 collapsed_sprints = ::ProjectSprint.where(project_id: project_id).where(
          "(start_date < ? AND end_date > ?) OR (start_date < ? AND end_date > ?) OR (start_date > ? AND end_date < ?)",
          start_date, start_date, end_date, end_date, start_date, end_date
        )
        startDate.AddError("is duplicate with another sprints") if collapsed_sprints.present?

2024-04-01 16:35 UTC, bachdx2812 commented on repository/projectSprint.repo.go
> +	endDate := projectSprint.EndDate.Format("2006-01-02")
define cái `2006-01-02` này trong constants

2024-04-01 16:36 UTC, bachdx2812 commented on validators/projectSprintCreate.form.go
> +	startDate.ValidateFormat("1-2-2006", "%d-%m-%y")
sử dụng biến trong constants, nếu chưa có thì define vào

2024-04-01 16:38 UTC, bachdx2812 commented on validators/projectSprintCreate.form.go
> +	sprintError := form.Repo.CollapsedSprints(&projectSprint)
đổi tên thành `FindCollapsedSprints`

xong r dùng cú pháp rút gọn

if err := form.Repo.CollapsedSprints(&projectSprint); err == nil {

2024-04-02 06:58 UTC, merged